import Head from 'next/head';
import Navbar from '../components/Navbar';
import Test from '../components/test'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sabrun.uz | Save Money. Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/smallLogo.ico" />
      </Head>
      <main>
        <Navbar />
      </main>
      <main>
        <Test/>
      </main>
    </>
  )
}
